# Generated by Django 2.2.3 on 2019-07-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shoe_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
